[package]
name = "sensor_rust"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
memoffset = "0.5.4"
rand = "0.8.4"
statrs = "0.15.0"

[dependencies.modellib]
path = "../../../src/core/modellib"

[lib]
crate-type = ["dylib"]
