[package]
name = "sensor_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
memoffset = "0.5.4"

[dependencies.modellib]
path = "/Users/kellyschultz/Documents/code/rsis/src/core/modellib"

[lib]
crate-type = ["dylib"]
