/* Autogenerated by RSIS Framework */
#include <cstdint>
#include <complex>
#include "BaseModel.hxx"

class PWMParams {
public:
    PWMParams();
    virtual ~PWMParams();
    double period; // Period 
    double duty; // Duty Cycle 
    int64_t initial_phase; // Phase offset 
};
class PWMData {
public:
    PWMData();
    virtual ~PWMData();
    double counter; // Counter used for calculating duty 
};
class PWMOut {
public:
    PWMOut();
    virtual ~PWMOut();
    double pwm; // PWM signal 
};
class PWMIn {
public:
    PWMIn();
    virtual ~PWMIn();
};
void Reflect_PWM();
