/* Autogenerated by RSIS Framework */
#include "PWM_interface.hxx"
PWMParams::PWMParams() : period(1.0), duty(0.5), initial_phase(0){ }
PWMParams::~PWMParams() { }
PWMData::PWMData() : counter(0.0){ }
PWMData::~PWMData() { }
PWMOut::PWMOut() : pwm(0.0){ }
PWMOut::~PWMOut() { }
PWMIn::PWMIn(){ }
PWMIn::~PWMIn() { }
void Reflect_PWM() {
}
