# Simple configuration file built with core utilities
# Primarily meant to test scenario setup from a file 
models:
  unitconversion:
    c1:
      freq: 3.0 # default thread is thread 0
      params:
        input_units: cm^3/s
        output_units: ft^3/minute
    c2:
      freq: 6.0
      params:
        input_units: ft^3/minute
        output_units: inch^3/s

connections:
  c1:
    signal: [c2, signal]

datalogging:
  c1:
    output: [signal]
