# Model Interface
# Used for exposing models & generating C++ interface code

module MModel

export Model, Port, Callback
export listcallbacks, triggercallback
export generateinterface

using ..MScripting

"""
Used to define a Port in a Model Interface file
"""
struct Port
    type::Type
    dimension::Tuple
    defaultvalue::Any
    units::String
    description::String

    function Port(type, dimension, defaultvalue, units, description)
        if eltype(defaultvalue) != type
            error("Default value does not match type")
        end
        _size = size(defaultvalue)
        if length(dimension) != length(_size)
            error("Provided dimension, [$dimension], does not match: $defaultvalue")
        end
        for i = 1:length(dimension)
            if dimension[i] != _size[i]
                error("Provided dimension, [$dimension], does not match: $defaultvalue")
            end
        end
        new(type, dimension, defaultvalue, units, description)
    end
end

"""
Used to define a Port Pointer in a Model Interface file
"""
struct PortPointer
    type::Type
    dimension::Tuple
    units::String
    description::String
end

"""
"""
struct Callback
    name::String
end

"""
References instantiated model in the simulation framework
"""
mutable struct Model
    name::String
    in::Vector{Any}
    out::Vector{Any}
    data::Vector{Any}
    params::Vector{Any}

    callbacks::Vector{Callback}
end

"""
    listcallbacks(model::Model)
List all callbacks provided by model instance
```jldoctest
julia> listcallbacks(mymodel)
mymodel callbacks:
    > configModel
    > initModel
    > stepModel
    > destroyModel
    > step_1Hz
```
"""
function listcallbacks(model::Model)
    name = model.name
    println("$name callbacks:")
    for i in eachindex(model.callbacks)
        cb = model.callbacks[i].name
        println("    > $cb")
    end
end

"""
    triggercallback(model::Model, callback::String)
Trigger a specified callback in a model instance.
```jldoctest
julia> triggercallback(mymodel, "step_1Hz")
[mymodel.step_1Hz] executed successfully.
```
"""
function triggercallback(model::Model, callback::String)
    println("Not implemented")
end

"""
    load(library::String)
Load a shared library containing a model implementation
```jldoctest
julia> load("mymodel")
Loaded: libmymodel.dylib
```
"""
function load(library::String)
    # Find library in search path, then pass absolute filepath
    # to core functionality
end

function createmodel(model::String)
    println("Not implemented")
    # call core::LoadModel
end

function connect(output::String, input::String)
    println("Not implemented")
end

"""
    generateinterface(interface::String)
Generate a C++ model interface from the specified interface file.
The generated files are put in the same location as the interface
file.
```jldoctest
julia> generateinterface("mymodel.jl")
Generating interface for mymodel
Generation complete
```
"""
function generateinterface(interface::String)
    path_interface = search(interface)
    if length(path_interface) == 0
        throw(IOError("Unable to find interface file: $interface"))
    end
    base_dir = dirname(path_interface[1])
    model_name = splitext(interface)[1]

    # Module cxx File
    n_module = model_name * "Module.cxx"
    f_path   = joinpath(base_dir, n_module)
    f_module = open(f_path, "w")
    write(f_module, "/* Autogenerated by RSIS Framework */")

    close(f_module)
    println("Generated: $f_path")

    # Model hxx file

    println("Generation complete")
    return
end

end
