[package]
name = "rsis"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
data-buffer = "0.8.0"

[dependencies.modellib]
path = "modellib"

[lib]
crate-type = ["dylib"]
