
# Provides the RSIS core framework access to the Logging module
module MEvents

export clear_event_map, add_event_map, get_event

using ..Logging

# globals
_event_map = Dict{Int64, String}();

# types
function clear_event_map()
    _event_map = Dict{Int64, String}();
end

"""
    add_event(id::Int64, message::String)
Define an event that can be generated by the framework
```jldoctest```
"""
function add_event(id::Int64, message::String) :: Nothing
    if id in keys(_event_map)
        @warn "ID($id) overwritten"
    end
    _event_map[id] = message;
end

function get_event(id::Int64) :: String
    get(_event_map, id, "Unknown Event")
end

end